services:
  postgres:
    image: postgres:17
    container_name: mocion-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: Administrador
      POSTGRES_PASSWORD: mocion2026
      POSTGRES_DB: mocion

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
  